version: '3.9'
services:
  downloadpostgres:
    container_name: download-postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bZ+XdvLx45M=
      - POSTGRES_DB=downloaddb
    ports:
      - "5435:5435"
    command: -p 5435
    expose:
      - 5435
    networks:
      - internal-network
  downloadmicroservice:
    container_name: download-microservice
    depends_on:
      - downloadpostgres
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8081:8081"
    expose:
      - 8081
    networks:
      - internal-network
      - inter-server-communication

networks:
  inter-server-communication:
    external: true
  internal-network:
    name: internal-network
    driver: bridge